const publicEnvKeys = [
  "NEXT_PUBLIC_APP_URL",
  "NEXT_PUBLIC_FIREBASE_API_KEY",
  "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN",
  "NEXT_PUBLIC_FIREBASE_PROJECT_ID",
  "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET",
  "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID",
  "NEXT_PUBLIC_FIREBASE_APP_ID",
  "NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST",
  "NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY",
  "NEXT_PUBLIC_SOLANA_NETWORK"
] as const;

const serverEnvKeys = [
  "SUPER_ADMIN_EMAIL",
  "FIREBASE_SERVICE_ACCOUNT_KEY",
  "PAYSTACK_SECRET_KEY",
  "PAYSTACK_WEBHOOK_SECRET",
  "PAYSTACK_DEFAULT_MONTHLY_PLAN_CODE",
  "SOLANA_RPC_URL",
  "SOLANA_USDC_MINT",
  "PLATFORM_SOLANA_USDC_WALLET",
  "SOLANA_PAYMENT_QUOTE_TTL_SECONDS",
  "SOLANA_USDC_NGN_FX_RATE",
  "GOOGLE_APPLICATION_CREDENTIALS",
  "KMS_KEY_RING",
  "KMS_ROOT_KEY",
  "RESEND_API_KEY",
  "RESEND_FROM_ADDRESS"
] as const;

export const envTemplate = {
  public: publicEnvKeys,
  server: serverEnvKeys
} as const;

export function readPublicEnv() {
  return {
    appUrl: process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000",
    firebaseProjectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID ?? "",
    firebaseAuthEmulatorHost: process.env.NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST ?? "",
    solanaNetwork: process.env.NEXT_PUBLIC_SOLANA_NETWORK ?? "devnet"
  };
}
